[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["graphs", "linkedlist"]

[tool.mypy]
strict = true

[tool.pytest.ini_options]
python_files = "*.py"
norecursedirs = ".venv legacy"
